# Generated by Django 4.0.3 on 2022-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('title', models.CharField(max_length=128, verbose_name='件名')),
                ('contents', models.TextField(verbose_name='内容')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='お問い合わせ日時')),
            ],
        ),
    ]
